services:
  aspnetfilrouge:
    container_name: filrouge-admin
    build:
      context: .
      dockerfile: AspNet_FilRouge/Dockerfile
    platform: linux/arm/v7
    ports:
      - "5100:5100"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5100"
      ASPNETCORE_ENVIRONMENT: "Production"
      Sync__SharedDbPath: "/data/aspnet-filrouge.shared.db"
      SeedUsers__AdminPassword: "ChangeMe_Admin_123!"
    volumes:
      - filrouge_data:/data
    restart: unless-stopped

  aspnetfilrougevendeur:
    container_name: filrouge-vendeur
    build:
      context: .
      dockerfile: AspNet_FilRouge_Vendeur/Dockerfile
    platform: linux/arm/v7
    ports:
      - "5101:5101"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5101"
      ASPNETCORE_ENVIRONMENT: "Production"
      Sync__SharedDbPath: "/data/aspnet-filrouge.shared.db"
      SeedUsers__VendeurPassword: "ChangeMe_Vendeur_123!"
      SeedUsers__AdminPassword: "ChangeMe_Admin_123!"
    volumes:
      - filrouge_data:/data
    restart: unless-stopped

volumes:
  filrouge_data: