services:
  aspnetfilrouge:
    container_name: filrouge-admin
    build:
      context: .
      dockerfile: AspNet_FilRouge/Dockerfile
    platform: linux/arm/v7
    ports:
      - "5100:5100"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5100"
      SeedUsers__AdminPassword: "MotDePasseAdmin123!"
    restart: unless-stopped

  aspnetfilrougevendeur:
    container_name: filrouge-vendeur
    build:
      context: .
      dockerfile: AspNet_FilRouge_Vendeur/Dockerfile
    platform: linux/arm/v7
    ports:
      - "5101:5101"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5101"
      SeedUsers__VendeurPassword: "MotDePasseSeller123!"
    restart: unless-stopped